[build]
  base = "./"
  command = "npm run netlify"
  publish = "__sapper__/export/"
  functions = "src/server/functions/"

[build.environment]
  TEST = "test"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/signupinit.json/*"
  to = "/.netlify/functions/signupinit"
  status = 200
  force = true

[[headers]]
  for = "/_digits/*.png"
  [headers.values]
    cache-control = "public,s-maxage=36000"
[[headers]]
  for = "/*.png"
  [headers.values]
    cache-control = "public,s-maxage=36000"
[[headers]]
  for = "/*.svg"
  [headers.values]
    cache-control = "public,s-maxage=36000"
[[headers]]
  for = "/*.ico"
  [headers.values]
    cache-control = "public,s-maxage=36000"
[[headers]]
  for = "/global.css"
  [headers.values]
    cache-control = "public,s-maxage=36000"

# end.
