#! /bin/bash
# Time-stamp: "2021-01-23 16:28:25 queinnec"

# Build the P server on Vercel.
# api/p.js should already exist to be taken into account.

# On Vercel, project settings are:
#    build command:     npm run vercel
#    output directory:  __sapper__/export
#    install command:   npm ci
# no development command (default is sapper dev --port $PORT)
# no root directory (default /)

# Tab Source Output shows a thorough reorganization of the files:
#   + _digits/*.png
#   + api/p.js
#   + client/*.{js,css}
#   favicon.{ico,png}
#   fw4ex-*.png
#   global.css
#   index.html                    // generated by sapper export
#   manifest.json
#   service-worker-index.html     // generated by sapper export
#   service-worker.js
# So, static/ is exported
#     __sapper__/export is moved into static/client
#     api/ is moved into static/
# Something like:
#    cp __sapper__/export/*   static/client/
#    cp api/*.js              static/api/
# then export all files from the static/ directory.

# When manually deployed (see Makefile deploy.vercel.manually), the
# WOGIT (i.e. without GIT) is true. This script is run on the dev machine
# to entirely prepare the server.

# if ${WOGIT:-false}
# then
#     echo "*** This is a manual deployment, ready to be used!"
#     exec /bin/true
# fi

# Erase some previous cached files:
if [ -d __sapper__ -o -d api/__sapper__ ]
then
    rm -rf __sapper__ api
fi

showls () {
    echo "*** ls -tal $1"
    ls -tal $1
}

cat > src/server.js <<EOF
import sirv from 'sirv';
import polka from 'polka';
import compression from 'compression';
import * as sapper from '@sapper/server';
import { CodeGradX } from 'codegradx';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

const serverless = require('serverless-http');
const server = polka() // You can also use Express
        .use(
                compression({ threshold: 0 }),
                sirv('static', { dev }),
                sapper.middleware()
        );
const handler = serverless(server);

module.exports.handler = async function (event, context) {
   console.log('entering handler...');
   const result = await handler(event, context);
   console.log('exiting handler');
   return result;
};
EOF

echo "*** Building the p.codegradx.org dynamic server..."
npm run build
showls `pwd`/
showls __sapper__/
#showls __sapper__/export/
showls __sapper__/build/

( sed -i.bak \
      -e 's@__sapper__/build@./__sapper__/build@' \
      __sapper__/build/server/server.js && \
  rm __sapper__/build/server/server.js.bak )

echo "*** Building the p.codegradx.org static server..."
npm run export
showls `pwd`/
showls __sapper__/
showls __sapper__/export/

if [ ! -f __sapper__/export/index.html ]
then
    echo "!!!!! Crawling phase missing!" >&2
    exit 1
fi

mkdir -p __sapper__/export/__sapper__/
mv __sapper__/build __sapper__/export/__sapper__/

#mkdir -p api
#cp -p __sapper__/export/server/server.js api/p.js

echo "*** end of wogit-vercel-build.sh"

# end of vercel-build.sh
